2023-01-23 22:51:25,608 - files.py - write 911 bytes to './exemplars/augmentation_tests/rbs_small_both_aug/outputs/autokeras/binary_classification/final_autokeras_classification_graph'
2023-01-23 22:51:25,608 - backend.py - run ['dot', '-Kdot', '-Tpdf', '-O', 'final_autokeras_classification_graph']
2023-01-23 22:51:26,010 - files.py - write 4424 bytes to './exemplars/augmentation_tests/rbs_small_both_aug/outputs/autokeras/binary_classification/final_autokeras_classification_graph'
2023-01-23 22:51:26,011 - backend.py - run ['dot', '-Kdot', '-Tpdf', '-O', 'final_autokeras_classification_graph']
2023-01-23 22:51:26,359 - files.py - write 30160 bytes to './exemplars/augmentation_tests/rbs_small_both_aug/outputs/autokeras/binary_classification/final_autokeras_classification_graph'
2023-01-23 22:51:26,359 - backend.py - run ['dot', '-Kdot', '-Tpdf', '-O', 'final_autokeras_classification_graph']
2023-01-24 03:12:37,666 - connectionpool.py - Starting new HTTPS connection (1): pypi.org:443
2023-01-24 03:12:37,797 - connectionpool.py - https://pypi.org:443 "GET /pypi/tpot/json HTTP/1.1" 200 12517
2023-01-24 03:59:39,542 - utils.py - Code block execution exceeded 10 seconds timeout
Traceback (most recent call last):
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/stopit/utils.py", line 145, in wrapper
    result = func(*args, **kwargs)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/tpot/decorators.py", line 57, in time_limited_call
    func(*args)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/pipeline.py", line 335, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/ensemble/_gb.py", line 500, in fit
    sample_weight_val, begin_at_stage, monitor, X_idx_sorted)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/ensemble/_gb.py", line 557, in _fit_stages
    random_state, X_idx_sorted, X_csc, X_csr)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/ensemble/_gb.py", line 212, in _fit_stage
    check_input=False, X_idx_sorted=X_idx_sorted)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/tree/_classes.py", line 1246, in fit
    X_idx_sorted=X_idx_sorted)
  File "/anaconda2/envs/automl_py37/lib/python3.7/site-packages/sklearn/tree/_classes.py", line 375, in fit
    builder.build(self.tree_, X, y, sample_weight, X_idx_sorted)
stopit.utils.TimeoutException
